# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
print(np.__version__)

1.22.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
# Method 1

a = np.random.rand(2,3,5)
a

array([[[0.05559613, 0.28912903, 0.50921051, 0.73702421, 0.75019975],
        [0.44841314, 0.00547249, 0.65709576, 0.4536762 , 0.48085445],
        [0.45235092, 0.80204296, 0.59481122, 0.76451371, 0.6363687 ]],

       [[0.20975161, 0.75167807, 0.90586513, 0.0627187 , 0.5168815 ],
        [0.57808126, 0.34846785, 0.83239973, 0.27504084, 0.74167784],
        [0.14659929, 0.75105199, 0.28983518, 0.67075598, 0.25454182]]])

In [39]:
# Method 2

a = np.random.randint(100,size=(2,3,5))
a

array([[[61, 71, 24, 68,  1],
        [ 8, 49, 52, 97, 98],
        [92, 29, 71,  0,  6]],

       [[14, 59, 22, 58, 13],
        [56, 88, 11, 46,  0],
        [54, 42, 39, 36, 69]]])

In [16]:
# Method 3
a = np.random.randn(2,3,5)
a

array([[[ 7.93638130e-01, -1.21847727e+00, -7.09716295e-01,
          2.15391599e+00, -3.22377003e-01],
        [-1.64014965e+00, -4.54246613e-02,  1.60315541e-03,
         -1.35768268e+00,  9.04700349e-01],
        [-4.96217261e-02,  3.38699189e-01, -2.18856052e+00,
          8.34279481e-01,  1.21436141e+00]],

       [[ 7.21502247e-01,  1.32902121e+00, -5.26095204e-01,
          6.04811804e-01,  6.68138540e-01],
        [-2.44720393e-01, -3.75844461e-01,  7.52034706e-02,
          6.04445232e-01, -5.94647086e-01],
        [-6.01295109e-01, -5.11084700e-01, -1.31096526e+00,
         -6.37097248e-01, -2.07387970e-01]]])

#### 4. Print *a*.


In [40]:
# your code here
print(a)

[[[61 71 24 68  1]
  [ 8 49 52 97 98]
  [92 29 71  0  6]]

 [[14 59 22 58 13]
  [56 88 11 46  0]
  [54 42 39 36 69]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here

b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [20]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
# your code here

a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here

print(a + b)
#an error appears because a and b differ in shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here

c = np.reshape(b,(2,3,5))

c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [75]:
# your code/answer here
d = a+c
print(d)

[[[62. 72. 25. 69.  2.]
  [ 9. 50. 53. 98. 99.]
  [93. 30. 72.  1.  7.]]

 [[15. 60. 23. 59. 14.]
  [57. 89. 12. 47.  1.]
  [55. 43. 40. 37. 70.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [43]:
# your code/answer here

print(a)
print(d)

#every element of the array a has increased by 1 because of the sum with the array c.

[[[61 71 24 68  1]
  [ 8 49 52 97 98]
  [92 29 71  0  6]]

 [[14 59 22 58 13]
  [56 88 11 46  0]
  [54 42 39 36 69]]]
[[[62. 72. 25. 69.  2.]
  [ 9. 50. 53. 98. 99.]
  [93. 30. 72.  1.  7.]]

 [[15. 60. 23. 59. 14.]
  [57. 89. 12. 47.  1.]
  [55. 43. 40. 37. 70.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [44]:
# your code here

e = a*c
print(e)

[[[61. 71. 24. 68.  1.]
  [ 8. 49. 52. 97. 98.]
  [92. 29. 71.  0.  6.]]

 [[14. 59. 22. 58. 13.]
  [56. 88. 11. 46.  0.]
  [54. 42. 39. 36. 69.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [46]:
# your code/answer here

np.array_equiv(a,e) 

#a == e because c is an arrya composed only by 1s, so elements of e are only multiplied by 1.

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [50]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d)

print(f"max in d is {d_max}, min in d is {d_min} and mean in d is {d_mean}")

[[[62. 72. 25. 69.  2.]
  [ 9. 50. 53. 98. 99.]
  [93. 30. 72.  1.  7.]]

 [[15. 60. 23. 59. 14.]
  [57. 89. 12. 47.  1.]
  [55. 43. 40. 37. 70.]]]
max in d is 99.0, min in d is 1.0 and mean in d is 45.46666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [54]:
# your code here

f = np.empty((2,3,5))
f

array([[[62., 72., 25., 69.,  2.],
        [ 9., 50., 53., 98., 99.],
        [93., 30., 72.,  1.,  7.]],

       [[15., 60., 23., 59., 14.],
        [57., 89., 12., 47.,  1.],
        [55., 43., 40., 37., 70.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [79]:
# your code here
d_flat = d.flatten()
f_flat = f.flatten()

for i in range (len(d_flat)):
            if d_flat[i] > d_min and d_flat[i] < d_mean:
                f_flat[i] = 25
            
            elif d_flat[i] > d_mean and d_flat[i] < d_max:
                f_flat[i] = 75
                
            elif d_flat[i] == d_mean:
                f_flat[i] = 50
                
            elif d_flat[i] == d_min:
                f_flat[i] = 0
                
            elif d_flat[i] == d_max:
                f_flat[i] = 100

f = f_flat.reshape((2,3,5))

print(f"max in d is {d_max}, min in d is {d_min} and mean in d is {d_mean}")

print (d)

print(f)

max in d is 99.0, min in d is 1.0 and mean in d is 45.46666666666667
[[[62. 72. 25. 69.  2.]
  [ 9. 50. 53. 98. 99.]
  [93. 30. 72.  1.  7.]]

 [[15. 60. 23. 59. 14.]
  [57. 89. 12. 47.  1.]
  [55. 43. 40. 37. 70.]]]
[[[ 75.  75.  25.  75.  25.]
  [ 25.  75.  75.  75. 100.]
  [ 75.  25.  75.   0.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.   0.]
  [ 75.  25.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [85]:
# your code here
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_flat = d.flatten()
f_flat = f.flatten()


d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

for i in range (len(d_flat)):
            if d_flat[i] > d_min and d_flat[i] < d_mean:
                f_flat[i] = 25

            elif d_flat[i] > d_mean and d_flat[i] < d_max:
                f_flat[i] = 75

            elif d_flat[i] == d_mean:
                f_flat[i] = 50

            elif d_flat[i] == d_min:
                f_flat[i] = 0

            elif d_flat[i] == d_max:
                f_flat[i] = 100

f = f_flat.reshape((2,3,5))

print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [93]:
# your code here
f_flat = f_flat.astype(np.unicode_)

for i in range (len(d_flat)):
            if d_flat[i] > d_min and d_flat[i] < d_mean:
                f_flat[i] = "B"

            elif d_flat[i] > d_mean and d_flat[i] < d_max:
                f_flat[i] = "D"

            elif d_flat[i] == d_mean:
                f_flat[i] = "C"

            elif d_flat[i] == d_min:
                f_flat[i] = "A"

            elif d_flat[i] == d_max:
                f_flat[i] = "E"

f = f_flat.reshape((2,3,5))

print(f)

[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
